// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/chilly266futon/reviewer-assignment-service/internal/domain"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// PullRequestRepository is an autogenerated mock type for the PullRequestRepository type
type PullRequestRepository struct {
	mock.Mock
}

type PullRequestRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *PullRequestRepository) EXPECT() *PullRequestRepository_Expecter {
	return &PullRequestRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, pr, reviewerIDs
func (_m *PullRequestRepository) Create(ctx context.Context, pr *domain.PullRequest, reviewerIDs []string) error {
	ret := _m.Called(ctx, pr, reviewerIDs)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.PullRequest, []string) error); ok {
		r0 = rf(ctx, pr, reviewerIDs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PullRequestRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type PullRequestRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - pr *domain.PullRequest
//   - reviewerIDs []string
func (_e *PullRequestRepository_Expecter) Create(ctx interface{}, pr interface{}, reviewerIDs interface{}) *PullRequestRepository_Create_Call {
	return &PullRequestRepository_Create_Call{Call: _e.mock.On("Create", ctx, pr, reviewerIDs)}
}

func (_c *PullRequestRepository_Create_Call) Run(run func(ctx context.Context, pr *domain.PullRequest, reviewerIDs []string)) *PullRequestRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.PullRequest), args[2].([]string))
	})
	return _c
}

func (_c *PullRequestRepository_Create_Call) Return(_a0 error) *PullRequestRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PullRequestRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.PullRequest, []string) error) *PullRequestRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *PullRequestRepository) GetByID(ctx context.Context, id string) (*domain.PullRequest, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.PullRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.PullRequest, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.PullRequest); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.PullRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PullRequestRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type PullRequestRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *PullRequestRepository_Expecter) GetByID(ctx interface{}, id interface{}) *PullRequestRepository_GetByID_Call {
	return &PullRequestRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *PullRequestRepository_GetByID_Call) Run(run func(ctx context.Context, id string)) *PullRequestRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *PullRequestRepository_GetByID_Call) Return(_a0 *domain.PullRequest, _a1 error) *PullRequestRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PullRequestRepository_GetByID_Call) RunAndReturn(run func(context.Context, string) (*domain.PullRequest, error)) *PullRequestRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByReviewerID provides a mock function with given fields: ctx, reviewerID
func (_m *PullRequestRepository) GetByReviewerID(ctx context.Context, reviewerID string) ([]*domain.PullRequest, error) {
	ret := _m.Called(ctx, reviewerID)

	if len(ret) == 0 {
		panic("no return value specified for GetByReviewerID")
	}

	var r0 []*domain.PullRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*domain.PullRequest, error)); ok {
		return rf(ctx, reviewerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*domain.PullRequest); ok {
		r0 = rf(ctx, reviewerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.PullRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, reviewerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PullRequestRepository_GetByReviewerID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByReviewerID'
type PullRequestRepository_GetByReviewerID_Call struct {
	*mock.Call
}

// GetByReviewerID is a helper method to define mock.On call
//   - ctx context.Context
//   - reviewerID string
func (_e *PullRequestRepository_Expecter) GetByReviewerID(ctx interface{}, reviewerID interface{}) *PullRequestRepository_GetByReviewerID_Call {
	return &PullRequestRepository_GetByReviewerID_Call{Call: _e.mock.On("GetByReviewerID", ctx, reviewerID)}
}

func (_c *PullRequestRepository_GetByReviewerID_Call) Run(run func(ctx context.Context, reviewerID string)) *PullRequestRepository_GetByReviewerID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *PullRequestRepository_GetByReviewerID_Call) Return(_a0 []*domain.PullRequest, _a1 error) *PullRequestRepository_GetByReviewerID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PullRequestRepository_GetByReviewerID_Call) RunAndReturn(run func(context.Context, string) ([]*domain.PullRequest, error)) *PullRequestRepository_GetByReviewerID_Call {
	_c.Call.Return(run)
	return _c
}

// ReplaceReviewer provides a mock function with given fields: ctx, prID, oldUserID, newUserID
func (_m *PullRequestRepository) ReplaceReviewer(ctx context.Context, prID string, oldUserID string, newUserID string) error {
	ret := _m.Called(ctx, prID, oldUserID, newUserID)

	if len(ret) == 0 {
		panic("no return value specified for ReplaceReviewer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, prID, oldUserID, newUserID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PullRequestRepository_ReplaceReviewer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReplaceReviewer'
type PullRequestRepository_ReplaceReviewer_Call struct {
	*mock.Call
}

// ReplaceReviewer is a helper method to define mock.On call
//   - ctx context.Context
//   - prID string
//   - oldUserID string
//   - newUserID string
func (_e *PullRequestRepository_Expecter) ReplaceReviewer(ctx interface{}, prID interface{}, oldUserID interface{}, newUserID interface{}) *PullRequestRepository_ReplaceReviewer_Call {
	return &PullRequestRepository_ReplaceReviewer_Call{Call: _e.mock.On("ReplaceReviewer", ctx, prID, oldUserID, newUserID)}
}

func (_c *PullRequestRepository_ReplaceReviewer_Call) Run(run func(ctx context.Context, prID string, oldUserID string, newUserID string)) *PullRequestRepository_ReplaceReviewer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *PullRequestRepository_ReplaceReviewer_Call) Return(_a0 error) *PullRequestRepository_ReplaceReviewer_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PullRequestRepository_ReplaceReviewer_Call) RunAndReturn(run func(context.Context, string, string, string) error) *PullRequestRepository_ReplaceReviewer_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function with given fields: ctx, id, status, mergedAt
func (_m *PullRequestRepository) UpdateStatus(ctx context.Context, id string, status string, mergedAt *time.Time) error {
	ret := _m.Called(ctx, id, status, mergedAt)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *time.Time) error); ok {
		r0 = rf(ctx, id, status, mergedAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PullRequestRepository_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type PullRequestRepository_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - status string
//   - mergedAt *time.Time
func (_e *PullRequestRepository_Expecter) UpdateStatus(ctx interface{}, id interface{}, status interface{}, mergedAt interface{}) *PullRequestRepository_UpdateStatus_Call {
	return &PullRequestRepository_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, id, status, mergedAt)}
}

func (_c *PullRequestRepository_UpdateStatus_Call) Run(run func(ctx context.Context, id string, status string, mergedAt *time.Time)) *PullRequestRepository_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(*time.Time))
	})
	return _c
}

func (_c *PullRequestRepository_UpdateStatus_Call) Return(_a0 error) *PullRequestRepository_UpdateStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PullRequestRepository_UpdateStatus_Call) RunAndReturn(run func(context.Context, string, string, *time.Time) error) *PullRequestRepository_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewPullRequestRepository creates a new instance of PullRequestRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPullRequestRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PullRequestRepository {
	mock := &PullRequestRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
