// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/chilly266futon/reviewer-assignment-service/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// TeamRepository is an autogenerated mock type for the TeamRepository type
type TeamRepository struct {
	mock.Mock
}

type TeamRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *TeamRepository) EXPECT() *TeamRepository_Expecter {
	return &TeamRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, team
func (_m *TeamRepository) Create(ctx context.Context, team *domain.Team) error {
	ret := _m.Called(ctx, team)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Team) error); ok {
		r0 = rf(ctx, team)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TeamRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type TeamRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - team *domain.Team
func (_e *TeamRepository_Expecter) Create(ctx interface{}, team interface{}) *TeamRepository_Create_Call {
	return &TeamRepository_Create_Call{Call: _e.mock.On("Create", ctx, team)}
}

func (_c *TeamRepository_Create_Call) Run(run func(ctx context.Context, team *domain.Team)) *TeamRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Team))
	})
	return _c
}

func (_c *TeamRepository_Create_Call) Return(_a0 error) *TeamRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TeamRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.Team) error) *TeamRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *TeamRepository) GetByID(ctx context.Context, id int) (*domain.Team, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*domain.Team, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *domain.Team); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TeamRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type TeamRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *TeamRepository_Expecter) GetByID(ctx interface{}, id interface{}) *TeamRepository_GetByID_Call {
	return &TeamRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *TeamRepository_GetByID_Call) Run(run func(ctx context.Context, id int)) *TeamRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *TeamRepository_GetByID_Call) Return(_a0 *domain.Team, _a1 error) *TeamRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TeamRepository_GetByID_Call) RunAndReturn(run func(context.Context, int) (*domain.Team, error)) *TeamRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByName provides a mock function with given fields: ctx, name
func (_m *TeamRepository) GetByName(ctx context.Context, name string) (*domain.Team, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetByName")
	}

	var r0 *domain.Team
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Team, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Team); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Team)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TeamRepository_GetByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByName'
type TeamRepository_GetByName_Call struct {
	*mock.Call
}

// GetByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *TeamRepository_Expecter) GetByName(ctx interface{}, name interface{}) *TeamRepository_GetByName_Call {
	return &TeamRepository_GetByName_Call{Call: _e.mock.On("GetByName", ctx, name)}
}

func (_c *TeamRepository_GetByName_Call) Run(run func(ctx context.Context, name string)) *TeamRepository_GetByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *TeamRepository_GetByName_Call) Return(_a0 *domain.Team, _a1 error) *TeamRepository_GetByName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TeamRepository_GetByName_Call) RunAndReturn(run func(context.Context, string) (*domain.Team, error)) *TeamRepository_GetByName_Call {
	_c.Call.Return(run)
	return _c
}

// NewTeamRepository creates a new instance of TeamRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTeamRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TeamRepository {
	mock := &TeamRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
