// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/chilly266futon/reviewer-assignment-service/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// UserRepository is an autogenerated mock type for the UserRepository type
type UserRepository struct {
	mock.Mock
}

type UserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *UserRepository) EXPECT() *UserRepository_Expecter {
	return &UserRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, user
func (_m *UserRepository) Create(ctx context.Context, user *domain.User) error {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.User) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type UserRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - user *domain.User
func (_e *UserRepository_Expecter) Create(ctx interface{}, user interface{}) *UserRepository_Create_Call {
	return &UserRepository_Create_Call{Call: _e.mock.On("Create", ctx, user)}
}

func (_c *UserRepository_Create_Call) Run(run func(ctx context.Context, user *domain.User)) *UserRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.User))
	})
	return _c
}

func (_c *UserRepository_Create_Call) Return(_a0 error) *UserRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.User) error) *UserRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetActiveUsersByTeamID provides a mock function with given fields: ctx, teamID, excludedUserIDs
func (_m *UserRepository) GetActiveUsersByTeamID(ctx context.Context, teamID int, excludedUserIDs []string) ([]*domain.User, error) {
	ret := _m.Called(ctx, teamID, excludedUserIDs)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveUsersByTeamID")
	}

	var r0 []*domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, []string) ([]*domain.User, error)); ok {
		return rf(ctx, teamID, excludedUserIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, []string) []*domain.User); ok {
		r0 = rf(ctx, teamID, excludedUserIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, []string) error); ok {
		r1 = rf(ctx, teamID, excludedUserIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepository_GetActiveUsersByTeamID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActiveUsersByTeamID'
type UserRepository_GetActiveUsersByTeamID_Call struct {
	*mock.Call
}

// GetActiveUsersByTeamID is a helper method to define mock.On call
//   - ctx context.Context
//   - teamID int
//   - excludedUserIDs []string
func (_e *UserRepository_Expecter) GetActiveUsersByTeamID(ctx interface{}, teamID interface{}, excludedUserIDs interface{}) *UserRepository_GetActiveUsersByTeamID_Call {
	return &UserRepository_GetActiveUsersByTeamID_Call{Call: _e.mock.On("GetActiveUsersByTeamID", ctx, teamID, excludedUserIDs)}
}

func (_c *UserRepository_GetActiveUsersByTeamID_Call) Run(run func(ctx context.Context, teamID int, excludedUserIDs []string)) *UserRepository_GetActiveUsersByTeamID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].([]string))
	})
	return _c
}

func (_c *UserRepository_GetActiveUsersByTeamID_Call) Return(_a0 []*domain.User, _a1 error) *UserRepository_GetActiveUsersByTeamID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepository_GetActiveUsersByTeamID_Call) RunAndReturn(run func(context.Context, int, []string) ([]*domain.User, error)) *UserRepository_GetActiveUsersByTeamID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *UserRepository) GetByID(ctx context.Context, id string) (*domain.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.User); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type UserRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *UserRepository_Expecter) GetByID(ctx interface{}, id interface{}) *UserRepository_GetByID_Call {
	return &UserRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *UserRepository_GetByID_Call) Run(run func(ctx context.Context, id string)) *UserRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *UserRepository_GetByID_Call) Return(_a0 *domain.User, _a1 error) *UserRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepository_GetByID_Call) RunAndReturn(run func(context.Context, string) (*domain.User, error)) *UserRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateIsActive provides a mock function with given fields: ctx, id, isActive
func (_m *UserRepository) UpdateIsActive(ctx context.Context, id string, isActive bool) error {
	ret := _m.Called(ctx, id, isActive)

	if len(ret) == 0 {
		panic("no return value specified for UpdateIsActive")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, bool) error); ok {
		r0 = rf(ctx, id, isActive)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserRepository_UpdateIsActive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateIsActive'
type UserRepository_UpdateIsActive_Call struct {
	*mock.Call
}

// UpdateIsActive is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - isActive bool
func (_e *UserRepository_Expecter) UpdateIsActive(ctx interface{}, id interface{}, isActive interface{}) *UserRepository_UpdateIsActive_Call {
	return &UserRepository_UpdateIsActive_Call{Call: _e.mock.On("UpdateIsActive", ctx, id, isActive)}
}

func (_c *UserRepository_UpdateIsActive_Call) Run(run func(ctx context.Context, id string, isActive bool)) *UserRepository_UpdateIsActive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(bool))
	})
	return _c
}

func (_c *UserRepository_UpdateIsActive_Call) Return(_a0 error) *UserRepository_UpdateIsActive_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserRepository_UpdateIsActive_Call) RunAndReturn(run func(context.Context, string, bool) error) *UserRepository_UpdateIsActive_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserRepository creates a new instance of UserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRepository {
	mock := &UserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
